### ISSUE TITLE
Newer LLVM makes memset recursive

### ISSUE THREAD

**Issue by tari** [alexcrichton/rlibc#11]
I've discovered that recent rustc nightlies (since January 30 at least) are smart enough to optimize `memset` and possibly other functions provided here into calls to the corresponding intrinsic which makes them recurse infinitely.

I'm guessing it's related to the switch to LLVM 3.8 in [303892ee15](https://github.com/rust-lang/rust/commit/303892ee156e5c31222b10786e661abb24dcf241). I'm adopting a workaround with optimized assembly versions of these functions which are opaque to the optimizer, but that's not a portable nor particularly good solution.

**Comment by alexcrichton** [comment]
Hm, I wonder if the `#![no_builtins]` attribute was somehow broken as part of that upgrade? Or maybe it's a bug in LLVM? Not sure...

**Comment by tari** [comment]
Oh, I failed to notice `#![no_builtins]` so my code (using these implementations) didn't have it.

I compiled rlibc (rather than my own code) with the same compiler and that doesn't seem to happen, so it's a problem on my end. Sorry for the noise!
