### ISSUE TITLE
Improper casting to `isize` truncates large `usize` values

### ISSUE THREAD

**Issue by shepmaster** [alexcrichton/rlibc#13]
Using [`memset` as an example](https://github.com/alexcrichton/rlibc/blob/5fdc9822c7d47f1a791cd05ffad35a37540e7004/src/lib.rs#L61-L66):

``` rust
    let mut i = 0;
    while i < n {
        *s.offset(i as isize) = c as u8;
        i += 1;
    }
    return s;
```

Assume `usize` is a `u8` thus `isize` will be an `i8` with a maximum value of 127. If `n` is between 128 and 255, Bad Things will happen. Scale up as appropriate for the platform's `usize`.

**Comment by japaric** [comment]
One possible solution is to have a inner `imemcpy` function that takes an `n: isize` that's know to be positive. Then have the real `memcpy` call the `imemcpy` twice if the `n: usize` > `ISIZE_MAX`.

Basically something like this (untested):

``` rust
// Omitting return value for simplicity
pub unsafe extern fn memcpy(dest: *mut u8, src: *const u8, n: usize) {
    fn imemcpy(dest: *mut u8, src: *const u8, n: isize) {
        // ...
    }

    if n > isize::MAX as usize {
        imemcpy(dest, src, isize::MAX);
        imemcpy(dest.offset(isize::MAX), src.offset(isize::MAX), (n - isize::MAX as usize) as isize);
    } else {
        imemcpy(dest, src, n as isize)
    }
}
```

**Comment by shepmaster** [comment]
I also feel that this particular thing is something I run into more frequently than I expect. I wonder if  adding `offset_forwards(n: usize)` and `offset_backwards(n: usize)` methods to the pointers would be a better solution.

**Comment by japaric** [comment]
> Basically something like this (untested):

I tried re-implementing the functions like this but the generated assembly is horrible.

> I wonder if adding offset_forwards(n: usize) and offset_backwards(n: usize) methods to the pointers would be a better solution.

Probably. Those would have to be implemented as intrinsics just like `offset` is (supossedly to avoid problems with aliasing) but I'm not sure what they would lower to ... `offset` lowers to a GEP instruction but AFAICT that takes a *signed* offset.

**Comment by alexcrichton** [comment]
Hm it seems that if `usize == u8` then this would be the least of your problems, and otherwise you'd have to be setting over half the address space to make this be a problem? 

I wonder if other implementations handle this in some special fashion.

**Comment by shepmaster** [comment]
> if usize == u8

Yes, that was just an example to make the math more obvious. Sorry I was unclear.

> you'd have to be setting over half the address space to make this be a problem?

Yes, but I don't see that it makes the problem any worse, it's just less likely. Saying that "most of the time people dereference valid pointers" doesn't lessen the problem when they do.

**Comment by bluss** [comment]
It's debatable if the cast to isize is improper. It doesn't lose any information. Gankro did a good breakdown here, which was the result of some discussion back and forth about how to read that darn LLVM doc:

https://github.com/Gankro/rfcs/blob/sharpie/text/0000-unsafe-pointer-reform.md#signed-offset

Anyway, the `.add(usize)` method is coming, currently unstable.

**Comment by alexcrichton** [comment]
I'm gonna close this as this repository is about to be archived in favor of `compiler-builtins`
