### ISSUE TITLE
-C lto removes functions

### ISSUE THREAD

**Issue by Zoxc** [alexcrichton/rlibc#15]
Doing `-C lto` will now remove the functions in this crate since they aren't directly used by anything (https://github.com/rust-lang/rust/issues/18134)

**Comment by Emilgardis** [comment]
Getting same thing, undefined references to panicking::panic.

**Comment by toothbrush7777777** [comment]
Is there any solution? At the moment I am including the functions in my crate.

**Comment by alexcrichton** [comment]
This is fixed with `compiler-builtins`, which I'm about to archive this project in favor of
