### ISSUE TITLE
Deprecate in favor of compiler-builtins

### ISSUE THREAD

**Issue by GabrielMajeri** [alexcrichton/rlibc#18]
Since the end of 2016, the [compiler-builtins](https://github.com/rust-lang-nursery/compiler-builtins/) crate has had its own [implementation](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/mem.rs) of the functions in this crate. For some architectures, they are even optimized with inline assembly.

It would make sense to clearly mark this crate as deprecated to prevent people from using it instead of the alternative.

**Comment by alexcrichton** [comment]
Sounds good to me! Would you be up for prepping a PR to update the README?
