### ISSUE TITLE
Add libcore as dependency in Cargo.toml

### ISSUE THREAD

**Issue by bharrisau** [alexcrichton/rlibc#2]
This might be a stretch (and I'm not sure what the Cargo plan for cross-compile stuff is), but as rlibc needs libcore can there be a way to build it?

I've hacked together this https://github.com/bharrisau/rust-libcore, for my mirror of rlibc (https://github.com/bharrisau/rust-librlibc). It should grab the matching source tarball for the rustc version and build libcore when it is missing.

**Comment by steveklabnik** [comment]
Update: using core through cargo is still a pain, though it can be worked around with things like http://www.randomhacks.net/2015/11/11/bare-metal-rust-custom-target-kernel-space/

**Comment by alexcrichton** [comment]
Yeah for now this isn't quite feasible without extra support from Cargo, so I'm going to close.
